version: '3.3'
services:
  post_db:
    image: mongo:3.2
    container_name: post_db
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${DOCKER_USERNAME}/ui:${UI_VERSION}
    container_name: ui
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${DOCKER_USERNAME}/post:${POST_VERSION}
    container_name: post
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${DOCKER_USERNAME}/comment:${COMMENT_VERSION}
    container_name: comment
    networks:
      - back_net
      - front_net
  prometheus:
    image: ${DOCKER_USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - back_net
      - front_net

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
    ipam:
      config:
        - subnet: "10.0.2.0/24"
  front_net:
    ipam:
      config:
        - subnet: "10.0.1.0/24"
