kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: cOnAgzvGl+Soci2YAQ5HKrHsLuMxLanCIXYhhubVA+w=
      - identity: {}
